version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 509399635098.dkr.ecr.eu-north-1.amazonaws.com
      - REPOSITORY_URI=509399635098.dkr.ecr.eu-north-1.amazonaws.com/loginwebapprepo
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Building the application...
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"loginwebapp-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
